apiVersion: v1
kind: Pod
metadata:
  name: registry-pod
  labels:
    app: registry
spec:
  containers:
    - name: registry
      image: registry:2
      ports:
        - containerPort: 5000
      volumeMounts:
        - name: auth-ssl-volume
          mountPath: "/ssl"
          readOnly: true
      volumeDevices:
        - name: registry-data-volume
          devicePath: /var/lib/registry
      env:
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_AUTH
          value: token
        - name: REGISTRY_AUTH_TOKEN_REALM
          value: https://localhost:5001/auth # the authentication server URI https://auth:5001/auth
        - name: REGISTRY_AUTH_TOKEN_SERVICE
          value: "registry"
        - name: REGISTRY_AUTH_TOKEN_ISSUER
          value: "auth_service" # Should be the same as token.issuer from authenticated-registry/config/auth_config.yml
        - name: REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE
          value: /ssl/server.pem
        - name: REGISTRY_HTTP_SECRET
          value: omgitsapseudorandomstringomglol

    - name: auth
      image: cesanta/docker_auth:1
      args: ["--v", "2" , "--alsologtostderr", "/config/auth_config.yml"]
    #   args: ["-c", "while true; do echo hello; sleep 10;done"]
      volumeMounts:
      - name: auth-ssl-volume
        mountPath: "/ssl"
        readOnly: true
      - name: auth-config-volume
        mountPath: "/config"
        readOnly: true
      ports:
        - containerPort: 5001
  volumes:
    - name: registry-data-volume
      persistentVolumeClaim:
        claimName: registry-data-pvc
    - name: auth-ssl-volume
      secret:
        secretName: auth-ssl-server
    - name: auth-config-volume
      secret:
        secretName: auth-config-secret
        

  