version: '2'

services:

    registry:
        image: registry:2.3
        ports:
            - 5000:5000
        volumes:
            - ./ssl:/ssl
            - ./registry-data:/var/lib/registry
            - ./auth:/auth
            #- ./config.yml:/etc/docker/registry/config.yml
        container_name: "registry"
        environment:
            - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
            - REGISTRY_AUTH=token
            - REGISTRY_AUTH_TOKEN_REALM=https://localhost:5001/auth # the authentication server URI https://auth:5001/auth
            - REGISTRY_AUTH_TOKEN_SERVICE="registry"
            - REGISTRY_AUTH_TOKEN_ISSUER="auth_service" # Should be the same as token.issuer from authenticated-registry/config/auth_config.yml
            - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/server.pem
            - REGISTRY_HTTP_SECRET=toto
            # - REGISTRY_AUTH=htpasswd
            # - REGISTRY_AUTH_HTPASSWD_REALM=Registry
            # - REGISTRY_AUTH_HTPASSWD_PATH=/auth/registry.password
        network_mode: host

    auth:
        image: cesanta/docker_auth:1
        ports:
            - 5001:5001
        volumes:
            - ./config:/config:ro
            - ./ssl:/ssl
            - ./logs:/logs
        command: --v=2 --alsologtostderr /config/auth_config.yml
        container_name: "auth"
        network_mode: host
            